server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true
  api.path: "http://localhost:8080/"
  #api.path: "http://localhost:8080/"

spring:
  datasource:
    username: 'izqquhtmakxwgq'
    password: '0d50569687c94c2d1d62c247d68b215ae0838aa282e152325f12c41eeaa3b73b'
    url: jdbc:postgresql://ec2-54-195-246-55.eu-west-1.compute.amazonaws.com/dabi719rot37t1
    driver-class-name: 'org.postgresql.Driver'

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'create-drop'
    show-sql: true
    open-in-view: true
#
#  minio:
#    url: https://practika2021.opencode.su:9000/
#    bucket: file #Minio Bucket name for app
#    access-key: pracktika2021
#    secret-key: KC8mmymg7vL3
#    secure: true
#
#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: google-client-id
#            client-secret: google-client-secret
#
#
