server:
  port: ${PORT:8080}
  error:
    whitelabel:
      enabled: true
# baseUrl: "http://localhost:8080/"
  adminEndPoint: "api/admin"
  userEndPoint: "api/user"
  swaggerEndPoint: "swagger-ui/#/"
  baseUrl: "https://joint-backend-dev.herokuapp.com/"

spring:
  datasource:
    username: 'rpaidzupqvagke'
    password: '16d7acd06b24bae62526f32d60da3571dd410a0ec2cf4006101ca15457b03709'
    url: jdbc:postgresql://ec2-52-214-125-106.eu-west-1.compute.amazonaws.com:5432/dba6u9lhf19566
    #url: jdbc:postgresql://ec2-54-195-246-55.eu-west-1.compute.amazonaws.com/dabi719rot37t1
    driver-class-name: 'org.postgresql.Driver'

  jpa:
    database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
    hibernate:
      ddl-auto: 'validate'
    show-sql: true
    open-in-view: true

jwt:
  token:
    secret: joint
    expired: 3600000
